### ISSUE TITLE
[Bug] Calendar doesn't show anything prior to the previous week

### ISSUE THREAD

**Issue by enchained** [CometTools/LunaSea#231] opened 2020-08-03 19:28 UTC
**Describe the Bug**
The calendar doesn't show anything prior to the previous week

**To Reproduce**
Open the calendar on week view on both Sonarr web and LunaSea. Click 2 times back on both. In my case, I have items on the July 20-26 week on the web, while LunaSea shows that I don't have any content for any of those days.
Is there an intentional 2-week limit for the past calendar display, or is this a bug?

**Expected Behaviour**
I would expect the calendar would display everything Sonarr displays on the web.

**Versions**
LunaSea TestFlight 3.2.0
Sonarr 3.0.3.904

**Comment by JagandeepBrar** [comment] 2020-08-04 03:19
This is currently by design, I will be adding the option to allow how many weeks in the past and in the future you can fetch data for. 

In the longterm future I hope I can add in dynamic fetching when you tap a date. I will be closing the issue though to try to keep the GitHub issues exclusive to bugs. I have opened a feedback board request for you here: https://feedback.lunasea.app/69

**Closed by JagandeepBrar** 2020-08-04 03:19 UTC
Labels: bug
